spring.application.name=entrenamiento_db
spring.datasource.url=jdbc:postgresql://localhost:5432/entrenamiento_db
spring.datasource.username=postgres
spring.datasource.password=050510

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Cambia temporalmente a 'update' para que Hibernate gestione la conexión libremente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
